name: Deploy to AWS EC2

on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@your-ec2-ip << 'EOF'
          cd project/EcoMart
          git pull origin main
          source env/bin/activate
          pip install -r requirements.txt
          python manage.py makemigrations
          python manage.py migrate
          sudo systemctl restart gunicorn
          sudo systemctl restart nginx
          EOF
