# Generated by Django 4.2.15 on 2024-12-20 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addproduct',
            name='shipping_price',
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='brand',
            field=models.CharField(choices=[('Titan', 'Titan'), ('Asos', 'Asos'), ('Zara', 'Zara'), ('River', 'River')], max_length=30),
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='discounted_price',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='gender',
            field=models.CharField(choices=[('Men', 'Men'), ('Unisex', 'Unisex'), ('Women', 'Women'), ('Kids', 'Kids')], max_length=6),
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='product_category',
            field=models.CharField(choices=[('Watch', 'Watch'), ('Clothing', 'Clothing'), ('Accessories', 'Accessories'), ('Shoes', 'Shoes')], max_length=30),
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='product_type',
            field=models.CharField(choices=[('Business_casual', 'Business_casual'), ('Wedding', 'Wedding'), ('Kurtas', 'Kurtas'), ('Formal', 'Formal'), ('Sports', 'Sports'), ('Casual', 'Casual')], max_length=20),
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
