# Generated by Django 4.2.15 on 2024-12-20 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_addproduct_shipping_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproduct',
            name='brand',
            field=models.CharField(choices=[('River', 'River'), ('Titan', 'Titan'), ('Asos', 'Asos'), ('Zara', 'Zara')], max_length=30),
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='discounted_price',
            field=models.FloatField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='gender',
            field=models.CharField(choices=[('Unisex', 'Unisex'), ('Men', 'Men'), ('Kids', 'Kids'), ('Women', 'Women')], max_length=6),
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='product_category',
            field=models.CharField(choices=[('Shoes', 'Shoes'), ('Accessories', 'Accessories'), ('Clothing', 'Clothing'), ('Watch', 'Watch')], max_length=30),
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='product_type',
            field=models.CharField(choices=[('Wedding', 'Wedding'), ('Kurtas', 'Kurtas'), ('Sports', 'Sports'), ('Business_casual', 'Business_casual'), ('Casual', 'Casual'), ('Formal', 'Formal')], max_length=20),
        ),
    ]
