# Generated by Django 4.2.15 on 2024-12-20 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_addproduct_brand_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addproduct',
            name='available_stock',
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='brand',
            field=models.CharField(choices=[('Zara', 'Zara'), ('Titan', 'Titan'), ('River', 'River'), ('Asos', 'Asos')], max_length=30),
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='gender',
            field=models.CharField(choices=[('Kids', 'Kids'), ('Unisex', 'Unisex'), ('Women', 'Women'), ('Men', 'Men')], max_length=6),
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='product_category',
            field=models.CharField(choices=[('Accessories', 'Accessories'), ('Shoes', 'Shoes'), ('Clothing', 'Clothing'), ('Watch', 'Watch')], max_length=30),
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='product_type',
            field=models.CharField(choices=[('Wedding', 'Wedding'), ('Sports', 'Sports'), ('Formal', 'Formal'), ('Kurtas', 'Kurtas'), ('Business_casual', 'Business_casual'), ('Casual', 'Casual')], max_length=20),
        ),
    ]
