# Generated by Django 4.2.15 on 2024-12-20 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_addproduct_available_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproduct',
            name='brand',
            field=models.CharField(choices=[('Asos', 'Asos'), ('Zara', 'Zara'), ('River', 'River'), ('Titan', 'Titan')], max_length=30),
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='gender',
            field=models.CharField(choices=[('Kids', 'Kids'), ('Women', 'Women'), ('Men', 'Men'), ('Unisex', 'Unisex')], max_length=6),
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='product_category',
            field=models.CharField(choices=[('Watch', 'Watch'), ('Accessories', 'Accessories'), ('Clothing', 'Clothing'), ('Shoes', 'Shoes')], max_length=30),
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='product_image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='product_type',
            field=models.CharField(choices=[('Business_casual', 'Business_casual'), ('Sports', 'Sports'), ('Wedding', 'Wedding'), ('Casual', 'Casual'), ('Kurtas', 'Kurtas'), ('Formal', 'Formal')], max_length=20),
        ),
    ]
