# Generated by Django 4.2.15 on 2024-12-20 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_addproduct_brand_alter_addproduct_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproduct',
            name='brand',
            field=models.CharField(choices=[('Zara', 'Zara'), ('River', 'River'), ('Asos', 'Asos'), ('Titan', 'Titan')], max_length=30),
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='product_category',
            field=models.CharField(choices=[('Clothing', 'Clothing'), ('Watch', 'Watch'), ('Accessories', 'Accessories'), ('Shoes', 'Shoes')], max_length=30),
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='product_type',
            field=models.CharField(choices=[('Formal', 'Formal'), ('Kurtas', 'Kurtas'), ('Sports', 'Sports'), ('Wedding', 'Wedding'), ('Business_casual', 'Business_casual'), ('Casual', 'Casual')], max_length=20),
        ),
    ]
