# Generated by Django 4.2.15 on 2024-12-20 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_addproduct_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproduct',
            name='product_image2',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='addproduct',
            name='product_image3',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='brand',
            field=models.CharField(choices=[('Titan', 'Titan'), ('Zara', 'Zara'), ('Asos', 'Asos'), ('River', 'River')], max_length=30),
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='gender',
            field=models.CharField(choices=[('Unisex', 'Unisex'), ('Men', 'Men'), ('Kids', 'Kids'), ('Women', 'Women')], max_length=6),
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='product_category',
            field=models.CharField(choices=[('Clothing', 'Clothing'), ('Accessories', 'Accessories'), ('Shoes', 'Shoes'), ('Watch', 'Watch')], max_length=30),
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='product_type',
            field=models.CharField(choices=[('Kurtas', 'Kurtas'), ('Formal', 'Formal'), ('Casual', 'Casual'), ('Sports', 'Sports'), ('Business_casual', 'Business_casual'), ('Wedding', 'Wedding')], max_length=20),
        ),
    ]
