# Generated by Django 4.2.15 on 2024-12-22 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_addproduct_brand_alter_addproduct_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproduct',
            name='brand',
            field=models.CharField(choices=[('River', 'River'), ('Asos', 'Asos'), ('Zara', 'Zara'), ('Titan', 'Titan')], max_length=30),
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='gender',
            field=models.CharField(choices=[('Men', 'Men'), ('Unisex', 'Unisex'), ('Women', 'Women'), ('Kids', 'Kids')], max_length=6),
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='product_category',
            field=models.CharField(choices=[('Shoes', 'Shoes'), ('Watch', 'Watch'), ('Accessories', 'Accessories'), ('Clothing', 'Clothing')], max_length=30),
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='product_type',
            field=models.CharField(choices=[('Casual', 'Casual'), ('Sports', 'Sports'), ('Business_casual', 'Business_casual'), ('Formal', 'Formal'), ('Wedding', 'Wedding'), ('Kurtas', 'Kurtas')], max_length=20),
        ),
    ]
