# Generated by Django 4.2.15 on 2024-12-22 18:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_addproduct_brand_alter_addproduct_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproduct',
            name='brand',
            field=models.CharField(choices=[('Zara', 'Zara'), ('River', 'River'), ('Asos', 'Asos'), ('Titan', 'Titan')], max_length=30),
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='gender',
            field=models.CharField(choices=[('Women', 'Women'), ('Kids', 'Kids'), ('Men', 'Men'), ('Unisex', 'Unisex')], max_length=6),
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='product_category',
            field=models.CharField(choices=[('Clothing', 'Clothing'), ('Shoes', 'Shoes'), ('Accessories', 'Accessories'), ('Watch', 'Watch')], max_length=30),
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='product_type',
            field=models.CharField(choices=[('Casual', 'Casual'), ('Wedding', 'Wedding'), ('Kurtas', 'Kurtas'), ('Formal', 'Formal'), ('Sports', 'Sports'), ('Business_casual', 'Business_casual')], max_length=20),
        ),
    ]
