# Generated by Django 4.2.15 on 2024-12-22 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_addproduct_brand_alter_addproduct_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproduct',
            name='brand',
            field=models.CharField(choices=[('Titan', 'Titan'), ('Zara', 'Zara'), ('Asos', 'Asos'), ('River', 'River')], max_length=30),
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='gender',
            field=models.CharField(choices=[('Kids', 'Kids'), ('Men', 'Men'), ('Unisex', 'Unisex'), ('Women', 'Women')], max_length=6),
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='product_category',
            field=models.CharField(choices=[('Accessories', 'Accessories'), ('Clothing', 'Clothing'), ('Shoes', 'Shoes'), ('Watch', 'Watch')], max_length=30),
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='product_type',
            field=models.CharField(choices=[('Casual', 'Casual'), ('Kurtas', 'Kurtas'), ('Sports', 'Sports'), ('Business_casual', 'Business_casual'), ('Wedding', 'Wedding'), ('Formal', 'Formal')], max_length=20),
        ),
    ]
