# Generated by Django 5.1.4 on 2025-01-17 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_addproduct_brand_alter_addproduct_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproduct',
            name='gender',
            field=models.CharField(choices=[('Men', 'Men'), ('Unisex', 'Unisex'), ('Kids', 'Kids'), ('Women', 'Women')], max_length=6),
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='product_category',
            field=models.CharField(choices=[('Clothing', 'Clothing'), ('Accessories', 'Accessories'), ('Watch', 'Watch'), ('Shoes', 'Shoes')], max_length=30),
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='product_type',
            field=models.CharField(choices=[('Wedding', 'Wedding'), ('Sports', 'Sports'), ('Casual', 'Casual'), ('Formal', 'Formal'), ('Kurtas', 'Kurtas'), ('Business_casual', 'Business_casual')], max_length=20),
        ),
    ]
