# Generated by Django 5.1.4 on 2025-01-17 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_addproduct_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproduct',
            name='brand',
            field=models.CharField(choices=[('Zara', 'Zara'), ('Asos', 'Asos'), ('River', 'River'), ('Titan', 'Titan')], max_length=30),
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='gender',
            field=models.CharField(choices=[('Unisex', 'Unisex'), ('Men', 'Men'), ('Kids', 'Kids'), ('Women', 'Women')], max_length=6),
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='product_category',
            field=models.CharField(choices=[('Watch', 'Watch'), ('Shoes', 'Shoes'), ('Accessories', 'Accessories'), ('Clothing', 'Clothing')], max_length=30),
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='product_type',
            field=models.CharField(choices=[('Sports', 'Sports'), ('Kurtas', 'Kurtas'), ('Business_casual', 'Business_casual'), ('Wedding', 'Wedding'), ('Formal', 'Formal'), ('Casual', 'Casual')], max_length=20),
        ),
    ]
